### ISSUE TITLE
Disable codecov PR comment

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/diffmin#49]
The PR comment posted by Codecov is too noisy to be helpful imo. We just want the checks to see that coverage doesn't decrease. If one wants to get the report, it can be found by clicking one of the status checks for details.

To disable checks, one can take the default `codecov.yml`:

```yaml
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
```

And replace the `comment` section at the end with `comment: false`.

```diff
-comment:
-  layout: "reach,diff,flags,files,footer"
-  behavior: default
-  require_changes: no
+comment: false
```
